arch:
  - amd64
  - ppc64le
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
jobs:
  include:
    - python: "pypy3"
      env: NOMYPY=true
install:
  - pip install flake8
  - "[[ \"$NOMYPY\" == true ]] || pip install mypy"
script:
  - nosetests
  - flake8
  - "[[ \"$NOMYPY\" == true ]] || mypy arpy.py"
